### ISSUE TITLE
전체적인 수정 및 세부 MyPage 구현

### ISSUE THREAD

**Issue by leeeyez** [Likelion-at-SMWU-11th/LoveBridge-Client#11]
## 📌  Feature Issue

윈도우pc에서 봤을 때 스타일 깨짐 수정하기
세부 mypage 수정 및 구현

## 📝  To-do

- [x] applypage 항목박스 px로 고치기
- [x] applycard px 대신 vw vh로 수정
- [x] myapplypage step 부분 구현
- [x] mydocpage 파일 이름 가져와보기
- [x] applypage select 항목 백으로 보내는 코드
