### ISSUE TITLE
ApplyPage,MyPage 구현 중

### ISSUE THREAD

**Issue by leeeyez** [Likelion-at-SMWU-11th/LoveBridge-Client#9]
## 📌  Feature Issue

ApplyPage,MyPage 구현 중
Topbar 오류도 수정하기

## 📝  To-do

- [x] topbar 각 페이지 이동할 때 보라색 선 나타나는 여부가 이상함 -> 수정하기
- [x] applypage 초기화 기능 구현
- [x] applypage 페이지네이션 틀만 구현
- [x] mypage 구현
- [x] mydocpage 틀 구현
